apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: sync-notion-inbox
  namespace: default
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: "truenas.localdomain:5000/sync-notion-inbox:latest"
  imagePullPolicy: Always
  mainApplicationFile: "local:///opt/spark-apps/sync_notion_inbox.py"
  sparkVersion: "3.1.1"
  restartPolicy:
    type: Never
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.1.1
    serviceAccount: spark
  executor:
    cores: 1
    instances: 2
    memory: "512m"
    labels:
      version: 3.1.1
