apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: operation-ftbs

deploy:
  helm:
    # hooks:
    #   after:
    #   - host:
    #     # TODO: create the client.properties file for kafka
    #     # TODO: set necessary env variables
    #     # command: ["sh", "./scripts/create-kafka-creds.sh"]
    releases:
    - name: prom-stack
      repo: https://prometheus-community.github.io/helm-charts
      remoteChart: kube-prometheus-stack
      createNamespace: true
      namespace: monitoring
      setValues:
        serviceMonitor:
          enabled: true
          additionalLabels:
            release: prom-stack
        prometheus.prometheusSpec.scrapeConfigSelector:
          # This is required otherwise the scrapeconfigs were not being provisioned
          matchLabels:
            prometheus: system-monitoring-prometheus
